"""Refresh the injury/suspension news overlay from a free public injury tracker.

The news overlay (``news_items.json``) used to be hand-curated. This module
regenerates it automatically, with no LLM in the loop and no paid API:

1. Ask the forecaster itself which teams are the current top-N by title odds
   (a live Monte-Carlo simulation — so the set tracks the real bracket).
2. Scrape the current World Cup 2026 injury table from Soccer26Live.
3. Keep only injuries for the top-N teams, map source team names to this app's
   canonical team names, and write ``news_items.json``.

The serving layer then looks each absent player up in the fitted PlayerDeltas
artifact and subtracts their learned strength — exactly as before; only the
*source* of the list changes from hand-editing to this scrape.

Why this source
---------------
API-Football (the previous source) is unusable here: its free plan only exposes
seasons 2022–2024 and refuses World Cup 2026. Soccer26Live publishes a
WC-2026-specific injury/availability table with no API key or signup, organised
by national team, in a regular HTML table with machine-readable ``data-*``
attributes. The tradeoff is that it's an HTML scrape coupled to that page's
markup rather than a JSON API — so a layout change (missing table, zero rows) is
treated as a hard failure rather than silently overwriting the overlay.

Run via the CLI wrapper:  ``python scripts/refresh_news.py --help``
"""

from __future__ import annotations

import html as _html
import os
import re
import urllib.error
import urllib.request
from datetime import date, timedelta, timezone, datetime
from pathlib import Path

from forecaster.data import normalize_team

NEWS_PATH = Path(__file__).resolve().parent / "news_items.json"

# Drop injuries the tracker hasn't updated within this many days of "today": a
# row the source stopped touching weeks ago is almost always resolved or stale
# pre-tournament noise (e.g. a late-May fitness doubt is irrelevant deep in the
# July knockouts). The source stamps each row with a last-updated date, so this
# is a clean recency cut. Tunable via refresh(max_age_days=...) / --max-age-days.
DEFAULT_MAX_AGE_DAYS = 21

# Free, keyless, WC-2026-specific injury tracker. Overridable via env for tests.
SOURCE_URL = os.environ.get(
    "SOCCERBOARD_INJURY_URL", "https://soccer26live.com/world-cup-2026/injuries/"
)
SOURCE_LABEL = "Soccer26Live"
# A browser-like User-Agent: the default urllib UA is 403'd by the source (and by
# most public sites). Kept descriptive so the request is honest about who we are.
USER_AGENT = (
    "Mozilla/5.0 (compatible; SoccerBoard/1.0; World Cup 2026 forecaster; "
    "+https://github.com/)"
)

# Soccer26Live team names -> this app's canonical names, for the cases where the
# two differ. normalize_team() (TEAM_ALIASES) covers most (e.g. "Türkiye" ->
# "Turkey", "Cabo Verde" -> "Cape Verde", "Congo DR" -> "DR Congo"), so this only
# needs the residual mismatches the tracker might use.
SOURCE_TEAM_ALIASES = {
    "USA": "United States",
    "Côte d'Ivoire": "Ivory Coast",
    "Cote d'Ivoire": "Ivory Coast",
    "Bosnia": "Bosnia and Herzegovina",
    "Czechia": "Czech Republic",
}

DEFAULT_ABOUT = (
    "Current injury and suspension news for active competitions. Per team, a "
    "list of absent players with a description and source. The serving layer "
    "looks each player up in the fitted PlayerDeltas artifact (built from "
    "StatsBomb lineup data) and subtracts their learned attack/defense "
    "contribution from their team's effective strength. No tier or multiplier "
    "needed — the magnitude comes from the model. Regenerated by "
    "scripts/refresh_news.py from a free public injury tracker (Soccer26Live)."
)


class ApiError(RuntimeError):
    """A recoverable failure fetching or parsing the injury source."""


def source_team_to_app(name: str) -> str:
    """Map a Soccer26Live team name to this app's canonical team name."""
    name = (name or "").strip()
    return normalize_team(SOURCE_TEAM_ALIASES.get(name, name))


def top_title_odds_teams(competition: str, top: int, n: int) -> list[str]:
    """The current top-`top` teams by championship probability (live odds)."""
    # Imported lazily so the module (and its cheap pure functions) load without
    # dragging in numpy/scipy when they aren't needed (e.g. in self-tests).
    from forecaster import predictor

    sim = predictor.simulation(competition, mode="live", n=n)
    rows = sorted(sim["teams"], key=lambda r: r.get("champion", 0.0), reverse=True)
    return [r["team"] for r in rows[:top]]


# --- Scrape layer ------------------------------------------------------------
def fetch_page(url: str = SOURCE_URL, *, timeout: int = 30) -> str:
    """GET the injury-tracker page's HTML. Raises ApiError on transport failure."""
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            charset = resp.headers.get_content_charset() or "utf-8"
            return resp.read().decode(charset, "replace")
    except urllib.error.HTTPError as e:
        body = e.read().decode(errors="replace")[:300]
        raise ApiError(f"{url}: HTTP {e.code}: {body}") from e
    except (urllib.error.URLError, TimeoutError) as e:
        raise ApiError(f"{url}: {e}") from e


_TABLE_RE = re.compile(
    r'<table[^>]*\bid="s26wc-updates-table".*?</table>', re.S | re.I
)
_ROW_RE = re.compile(r"<tr\b([^>]*\bdata-player-name=[^>]*)>(.*?)</tr>", re.S | re.I)
_CELL_RE = re.compile(r"<td\b[^>]*>(.*?)</td>", re.S | re.I)
_STRONG_RE = re.compile(r"<strong[^>]*>(.*?)</strong>", re.S | re.I)


def _clean(fragment: str) -> str:
    """Strip HTML tags + entities from a fragment and collapse whitespace."""
    text = _html.unescape(re.sub(r"<[^>]+>", " ", fragment or ""))
    return re.sub(r"\s+", " ", text).strip()


def _attr(tag: str, name: str) -> str:
    m = re.search(name + r'="([^"]*)"', tag)
    return m.group(1) if m else ""


def _first_strong(cell: str) -> str:
    """Text of the first <strong> in a table cell (the display value), or ""."""
    m = _STRONG_RE.search(cell or "")
    return _clean(m.group(1)) if m else ""


def _row_updated_iso(tag: str, cells: list[str]) -> str:
    """The row's last-updated date as ISO (YYYY-MM-DD), or "" if unknown. Prefers
    the machine-readable ``data-updated`` unix timestamp, falling back to parsing
    the human 'UPDATED' column (e.g. "Jul 7, 2026")."""
    ts = _attr(tag, "data-updated")
    if ts.isdigit():
        return datetime.fromtimestamp(int(ts), tz=timezone.utc).date().isoformat()
    text = _clean(cells[5]) if len(cells) > 5 else ""
    for fmt in ("%b %d, %Y", "%B %d, %Y", "%d %b %Y"):
        try:
            return datetime.strptime(text, fmt).date().isoformat()
        except ValueError:
            continue
    return ""


def parse_injuries(html_text: str) -> list[dict]:
    """Parse the Soccer26Live injury table into raw per-player records.

    Pure function (no I/O) so it can be unit-tested against a captured page.
    Returns ``{player, team, injury, status, expected_return, updated}`` dicts.
    Raises ApiError if the table element is absent — a structural change we would
    rather surface loudly than paper over with an empty overlay."""
    tbl = _TABLE_RE.search(html_text or "")
    if not tbl:
        raise ApiError(
            "injuries table not found on the source page — its layout may have "
            "changed; refusing to overwrite the overlay with nothing."
        )
    records: list[dict] = []
    for tag, body in _ROW_RE.findall(tbl.group(0)):
        cells = _CELL_RE.findall(body)
        if len(cells) < 4:
            continue
        # Prefer the proper-case display text in each cell's <strong>; fall back
        # to the row's lowercase data-* attributes if a cell is malformed.
        player = _first_strong(cells[0]) or _clean(_attr(tag, "data-player-name")).title()
        team = _first_strong(cells[1]) or _clean(_attr(tag, "data-team-name")).title()
        injury = _first_strong(cells[2])
        status = (_attr(tag, "data-status") or _clean(cells[3])).lower()
        expected = _clean(cells[4]) if len(cells) > 4 else ""
        if not player or not team:
            continue
        records.append({
            "player": player,
            "team": team,
            "injury": injury,
            "status": status,
            "expected_return": expected,
            "updated": _row_updated_iso(tag, cells),
        })
    return records


def fetch_injuries(url: str = SOURCE_URL) -> list[dict]:
    """Fetch + parse the current injury table in one request."""
    records = parse_injuries(fetch_page(url))
    if not records:
        raise ApiError(
            f"parsed 0 injuries from {url} — the table structure may have "
            "changed; refusing to overwrite the overlay with nothing."
        )
    return records


def _issue_text(injury: str, status: str, expected_return: str) -> str:
    """A short human-readable description from the tracker's injury + status."""
    reason = (injury or "").strip()
    # The tracker uses these as placeholders when it has no real description.
    if (
        not reason
        or "specifics not detailed" in reason.lower()
        or reason.lower() in ("fitness check", "injury update")
    ):
        reason = ""
    status = (status or "").strip().lower()
    ruled_out = "ruled out" in (expected_return or "").lower()
    if status == "doubtful":
        return f"{reason} (a fitness doubt)" if reason else "a fitness doubt"
    # Anything else is treated as out/injured.
    if reason and ruled_out:
        return f"{reason}; ruled out of the tournament"
    if reason:
        return reason
    return "ruled out of the tournament" if ruled_out else "out injured"


def build_teams_news(
    records: list[dict],
    wanted_teams: list[str],
    *,
    as_of: str | None = None,
    max_age_days: int | None = DEFAULT_MAX_AGE_DAYS,
) -> dict[str, list[dict]]:
    """Turn raw injury records into the news_items ``teams`` map: keep only teams
    in `wanted_teams`, drop rows the source hasn't updated within `max_age_days`
    of `as_of` (default today; pass max_age_days=None to disable), and dedupe to
    one entry per player.

    Pure function (no I/O) so it can be unit-tested against captured records."""
    wanted = set(wanted_teams)
    cutoff = None
    if max_age_days is not None:
        ref = date.fromisoformat(as_of) if as_of else date.today()
        cutoff = (ref - timedelta(days=max_age_days)).isoformat()
    # team -> {player_key: item}, so a later record for a player replaces an
    # earlier one.
    buckets: dict[str, dict[str, dict]] = {}
    for rec in records:
        team = source_team_to_app(rec.get("team", ""))
        if team not in wanted:
            continue
        # Recency cut: a stale row (source hasn't touched it in weeks) is almost
        # always resolved or pre-tournament noise. A row with no parseable date
        # is kept (fail-open) so a missing timestamp never silently hides news.
        updated = rec.get("updated", "")
        if cutoff and updated and updated < cutoff:
            continue
        name = (rec.get("player") or "").strip()
        if not name:
            continue
        item = {
            "player": name,
            "issue": _issue_text(
                rec.get("injury", ""), rec.get("status", ""),
                rec.get("expected_return", ""),
            ),
            "source": SOURCE_LABEL,
            "url": SOURCE_URL,
        }
        buckets.setdefault(team, {})[name.lower()] = item
    return {team: list(items.values()) for team, items in sorted(buckets.items())}


def write_news(competition: str, teams_news: dict[str, list[dict]], path: Path | None = None) -> None:
    """Write `teams_news` for `competition` into news_items.json, preserving the
    ``_about`` note and any other competitions already in the file."""
    import json

    path = path or NEWS_PATH  # resolved at call time, so the module global wins
    doc = json.loads(path.read_text()) if path.exists() else {}
    doc.setdefault("_about", DEFAULT_ABOUT)
    doc[competition] = {
        "updated": date.today().isoformat(),
        "teams": teams_news,
    }
    path.write_text(json.dumps(doc, indent=2, ensure_ascii=False) + "\n")


def refresh(
    competition: str = "world_cup_2026",
    *,
    top: int = 10,
    season: int = 2026,
    n: int = 20000,
    max_age_days: int = DEFAULT_MAX_AGE_DAYS,
    dry_run: bool = False,
) -> dict:
    """Full pipeline: pick the top-N title-odds teams, scrape their injuries, drop
    stale rows, and (unless dry_run) rewrite news_items.json. Returns a summary.

    `season` is accepted for CLI compatibility but unused: the free source only
    covers the 2026 World Cup."""
    teams = top_title_odds_teams(competition, top, n)
    records = fetch_injuries()
    teams_news = build_teams_news(records, teams, max_age_days=max_age_days)
    if not dry_run:
        write_news(competition, teams_news)
    return {
        "competition": competition,
        "fetched_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "top_teams": teams,
        "records_fetched": len(records),
        "max_age_days": max_age_days,
        "teams_with_news": teams_news,
        "injuries_kept": sum(len(v) for v in teams_news.values()),
        "dry_run": dry_run,
    }
